# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

#osx_image: xcode7.3
#language: objective-c
# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
#script:
#- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/Euromsg.xcworkspace -scheme Euromsg-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
#- pod lib lint


language: swift
before_install:
  - gem uninstall fourflusher --force -a -q -I -x
  - gem install fourflusher
  - gem uninstall cocoapods --force -a -q -I -x
  - gem install cocoapods -v 1.6.1
osx_image: xcode11
before_script: cd Example
podfile: Example/Podfile
branches:
  only:
  - master
env:
  global:
  - WORKSPACE=Euromsg.xcworkspace
  - SCHEME=Euromsg-Example
  matrix:
    - DESTINATION="OS=13.0,name=iPhone 11"   SCHEME="$SCHEME"    RUN_TESTS="YES"     POD_LINT="YES"
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks

  # Build Framework in Debug and Run Tests if specified
  - if [ $RUN_TESTS == "YES" ]; then
      travis_retry xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty -c;
    else
      xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty -c;
    fi

  - xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO build | xcpretty -c;

  # Run `pod lib lint` if specified
  - if [ $POD_LINT == "YES" ]; then
      cd .. && pod lib lint --allow-warnings && cd MixpanelDemo;
    fi


